spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  retry:
    instances:
      productService:
        max-attempts: 3
        wait-duration: 500ms

  circuitbreaker:
    instances:
      productService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  endpoint:
    health:
      show-details: ALWAYS

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0


